name: 'Just'
description: "Execute a just target"
inputs:
  recipes:
    description: "Just Recipe(s) to execute"
    required: true
  env:
    description: "Environment variable file name to use"
    required: false
runs:
  using: "composite"
  steps:
    - name: Execute just target
      shell: bash
      env:
        recipes: ${{ inputs.recipes }}
        env_path: ${{ inputs.env_path }}
      run: |
        if [[ -n "$env_path" ]]; then
          just -E "$env_path.env" $recipes
        else
          just $recipes
        fi
